baseURL = "https://emilymassiel.github.io/"
languageCode = "en-us"
title = "♡ Emily's blog ♡"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hello there!!"
Content = "I am super happy to be here :D"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/EmilyMassiel"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/massielalfaro8"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/massiel01.0/"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30

